#!/usr/bin/env python3
"""
SQLite Table Explorer - MCP server to list tables and show table data from app.db SQLite file.
Version: 1.0
Generated by MCP Server Creator on 2025-09-18
"""

from fastmcp import FastMCP, Context

# Initialize the MCP server
mcp = FastMCP(
    "SQLite Table Explorer",
    instructions="""MCP server to list tables and show table data from app.db SQLite file."""
)

# Tool: List all tables in app.db
@mcp.tool()
def list_tables() -> list:
    """Lists all tables in the SQLite database app.db."""
    import sqlite3
    conn = sqlite3.connect('app.db')
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [row[0] for row in cursor.fetchall()]
    conn.close()
    return tables

# Tool: Get all data from a specified table
@mcp.tool()
def get_table_data(table_name: str) -> dict:
    """Returns all data from the specified table in the SQLite database app.db."""
    import sqlite3
    conn = sqlite3.connect('app.db')
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name}")
    rows = cursor.fetchall()
    columns = [description[0] for description in cursor.description]
    conn.close()
    return {'columns': columns, 'rows': rows}

if __name__ == "__main__":
    mcp.run()
